### ISSUE TITLE
How to call a rest api with berear token authentication from trust framework policy?

### ISSUE THREAD

**Issue by shahzaibafzalmughal** [beejones/B2CDemoTools#1]
Hi,
My scenario is, I've an API, Which uses bearer token authentication. For example:
We POST user credentials (Username & Password) to this endpoint: 
POST https://api.domain.com/authenticate
Body = {username : "xyz", password: "123456" }
This returns a Bearer token which we use send as authorization header in subsequent requests to API, Like this:
GET https://api.domain.com/GetAllProducts
Headers:
Authorization  = {Bearer TOKEN}
## How to do this in Trust Framework Policy?

I know to Call an API from Trust Framework We create a Claims Provider node and then define a technical profile for it. Technical Profiles allow standard protocols. I used "OAuth2". Below is my code:
`<TechnicalProfile Id="LoyaltyRest">
    <DisplayName>TEST CLAIM PROVIDER</DisplayName>
    <Protocol Name="OAuth2" />
    <Metadata>
        <Item Key="userinfo_endpoint">http://b2ctestapi.azurewebsites.net/api/loyalty</Item>
        <Item Key="BearerTokenTransmissionMethod">AuthorizationHeader</Item>
    </Metadata>
    <CryptographicKeys>
        <Key Id="BasicAuthenticationUsername" StorageReferenceId="B2cRestClientId" />
        <Key`Id="BasicAuthenticationPassword"`StorageReferenceId="B2cRestClientSecret" />
    </CryptographicKeys>
    <InputClaims>
        <InputClaim ClaimTypeReferenceId="userId" PartnerClaimType="userid" />
    </InputClaims>
    <OutputClaims>
        <OutputClaim ClaimTypeReferenceId="Loyalty" PartnerClaimType="LoyaltyNumber" />
    </OutputClaims>
    <UseTechnicalProfileForSessionManagement ReferenceId="SM-Noop" />
</TechnicalProfile>`

**Comment by gsacavdm** [comment]
Repo has moved, feel free to recreate this issue in the new repo.
https://github.com/Azure-Samples/active-directory-b2c-advanced-policies
