### ISSUE TITLE
Powershell command Get-TrustFramework -ListPolicies does not work

### ISSUE THREAD

**Issue by WhippsP** [beejones/B2CDemoTools#5]
Error being returned is 
`<Error><ExceptionMessage>User Authorization: TenantId parameter is missing in request</ExceptionMessage><CorrelationId>b5da28e2-df78-49a1-a9fc-1a83578a4fd3</CorrelationId></Error>`

It also uses the api/tenantPolicyList endoint rather than /api/policyList

/api/policylist?tenantId=myb2ctenanr.onmicrosoft.com works fine

Relates to: [B2CDemoTools/ExploreAdmin/ExploreAdmin.dll](https://github.com/beejones/B2CDemoTools/blob/master/ExploreAdmin/ExploreAdmin.dll)

**Comment by gsacavdm** [comment]
Repo has moved, feel free to recreate this issue in the new repo.
https://github.com/Azure-Samples/active-directory-b2c-advanced-policies
